### ISSUE TITLE
Could you provide the setting of training Deeplab on MSCOCO dataset?

### ISSUE THREAD

**Issue by Italy2006** [zhaozhengChen/LPCAM#3]

**Comment by zhaozhengChen** [comment]
Thanks for your interest in our work. This is the config file for training Deeplab on the MSCOCO dataset.
Compared to the config on VOC dataset, there are only a few modifications:  change the BATCH_SIZE to 10, ITER_MAX to 100000, and LR to 2e-4.
```
EXP:
    ID: coco
    OUTPUT_DIR: data_coco

DATASET:
    NAME: coco
    ROOT: ./data/datasets/coco_2014
    LABELS: ./data/datasets/coco_2014/mask
    N_CLASSES: 81
    IGNORE_LABEL: 255
    SCALES: [0.5, 0.75, 1.0, 1.25, 1.5]
    SPLIT:
        TRAIN: train2014
        VAL: val2014
        TEST: no

DATALOADER:
    NUM_WORKERS: 8

IMAGE:
    MEAN:
        R: 122.675
        G: 116.669
        B: 104.008
    SIZE:
        BASE: # None
        TRAIN: 321
        TEST: 513

MODEL:
    NAME: DeepLabV2_ResNet101_MSC
    N_BLOCKS: [3, 4, 23, 3]
    ATROUS_RATES: [6, 12, 18, 24]
    INIT_MODEL: data/models/imagenet/deeplabv1_resnet101-imagenet.pth

SOLVER:
    BATCH_SIZE:
        TRAIN: 10
        TEST: 1
    ITER_MAX: 100000
    ITER_SIZE: 2
    ITER_SAVE: 5000
    ITER_TB: 20
    LR_DECAY: 10
    LR: 2e-4
    MOMENTUM: 0.9
    OPTIMIZER: sgd
    POLY_POWER: 0.9
    WEIGHT_DECAY: 5.0e-4
    AVERAGE_LOSS: 20

CRF:
    ITER_MAX: 10
    POS_W: 3
    POS_XY_STD: 1
    BI_W: 4
    BI_XY_STD: 67
    BI_RGB_STD: 3
```
